//! Persistent pollution sector.
//!
//! Pollution is generated by industrial and agricultural activity, passes
//! through a 20-year appearance delay (World3-03 PPTD, Delay3), then accumulates
//! as persistent pollution. Assimilation rate decreases as pollution builds.
//!
//! Four ODE stocks: pollution_appearance_stage1, stage2, and
//! pollution_appearance_buffer (stage3) form the Delay3 pipeline;
//! persistent_pollution tracks appeared pollution affecting the environment.

use crate::lookup::tables::WorldLookupTables;
use crate::model::{params::ScenarioParams, state::WorldState};

/// Pollution generation coefficient per unit industrial output [index_units / USD].
/// Calibrated: at 1970 (industrial_output ≈ 1e12 USD/yr, iopc_norm ≈ 1.0):
///   gen_industry ≈ 1e12 × 3e-13 × 1.0 = 0.30 index_units/yr.
const PPGIO: f64 = 3.0e-13;

/// Pollution generation coefficient per unit of arable_land × inputs_per_ha.
const PPGAO: f64 = 1.0e-13;

/// Pollution appearance delay [years]. World3-03: PPTD = 20 years.
/// Generated pollution takes this long to become persistent (visible) pollution.
const POLLUTION_APPEARANCE_DELAY: f64 = 20.0;

/// Returns (d_persistent_pollution, d_stage1, d_stage2, d_stage3)
pub fn pollution_derivatives(
    state: &mut WorldState,
    params: &ScenarioParams,
    tables: &WorldLookupTables,
) -> (f64, f64, f64, f64) {
    // ---- Pollution generation ----
    // Normalize IOPC to ~1.0 at 1970 level. World3-03 IO70 = 7.9e11 → IOPC70 ≈ $220/person/yr.
    let iopc_normalized = state.capital.industrial_output_per_capita / 220.0;
    let agri_normalized = state.agriculture.agricultural_inputs_per_hectare / 40.0;

    let gen_industry = state.capital.industrial_output
        * PPGIO
        * tables.pollution_generation_industry.eval(iopc_normalized);

    let gen_agriculture = state.agriculture.arable_land
        * state.agriculture.agricultural_inputs_per_hectare
        * PPGAO
        * tables.pollution_generation_agriculture.eval(agri_normalized);

    // Pollution control policy reduces generation
    let control = params.pollution_control.clamp(0.0, 1.0);
    let generation = (gen_industry + gen_agriculture) * (1.0 - control);

    state.pollution.generation_rate = generation;

    // ---- 20-year appearance delay (Delay3: 3 cascaded pipeline stages) ----
    // World3-03: PPTD = 20yr. Delay3 gives pipeline-like transit behavior
    // (more uniform transit time than Delay1). Each stage τ = PPTD/3.
    let tau = POLLUTION_APPEARANCE_DELAY / 3.0;
    let flow_1_to_2 = state.pollution.pollution_appearance_stage1 / tau;
    let flow_2_to_3 = state.pollution.pollution_appearance_stage2 / tau;
    let appearance_rate = state.pollution.pollution_appearance_buffer / tau; // stage3 out

    // ---- Pollution assimilation ----
    let assimilation_time = tables
        .pollution_assimilation_time
        .eval(state.pollution.pollution_index);

    let assimilation = if assimilation_time > 0.0 {
        state.pollution.persistent_pollution / assimilation_time
    } else {
        0.0
    };
    state.pollution.assimilation_rate = assimilation;

    // ---- Update pollution index (auxiliary) ----
    // Pollution index equals the persistent_pollution stock directly.
    // The stock is pre-normalized so that 1.0 ≈ 1970 pollution level (calibrated
    // through PPGIO/PPGAO coefficients, not an explicit PPOL70 constant).
    // All lookup tables (assimilation_time, LYMAP, LMP) are calibrated against
    // this normalized scale.
    state.pollution.pollution_index = state.pollution.persistent_pollution.max(0.0);

    // d(stage1)/dt = generation - flow_1_to_2
    let d_stage1 = generation - flow_1_to_2;
    // d(stage2)/dt = flow_1_to_2 - flow_2_to_3
    let d_stage2 = flow_1_to_2 - flow_2_to_3;
    // d(stage3)/dt = flow_2_to_3 - appearance_rate  (stage3 = pollution_appearance_buffer)
    let d_stage3 = flow_2_to_3 - appearance_rate;
    // d(persistent_pollution)/dt = appearance_rate - assimilation
    let d_persistent = appearance_rate - assimilation;

    (d_persistent, d_stage1, d_stage2, d_stage3)
}

// REQ: REQ-001
#[cfg(test)]
mod tests {
    use super::*;
    use approx::assert_relative_eq;
    use crate::lookup::tables::WorldLookupTables;
    use crate::model::params::ScenarioParams;
    use crate::model::state::WorldState;

    fn setup() -> (WorldState, ScenarioParams, WorldLookupTables) {
        let mut s = WorldState::initial_1900();
        let params = ScenarioParams::collapse();
        let tables = WorldLookupTables::load();
        // Pre-populate industrial output
        s.capital.industrial_output = 2.1e11 / 3.0;
        s.capital.industrial_output_per_capita = s.capital.industrial_output / 1.6e9;
        s.agriculture.agricultural_inputs_per_hectare = 10.0;
        s.pollution.pollution_index = 0.05;
        s.pollution.persistent_pollution = 0.05;
        s.pollution.pollution_appearance_buffer = 0.05;
        (s, params, tables)
    }

    #[test]
    fn test_pollution_appearance_delay() {
        let (mut s, params, tables) = setup();
        let (d_persistent, d_stage1, d_stage2, d_stage3) = pollution_derivatives(&mut s, &params, &tables);
        // Generation feeds stage1, pipeline drains to persistent
        assert!(s.pollution.generation_rate > 0.0, "generation should be positive");
        assert!(d_stage1.is_finite());
        assert!(d_stage2.is_finite());
        assert!(d_stage3.is_finite());
        assert!(d_persistent.is_finite());
    }

    #[test]
    fn test_steady_state_pollution() {
        let (mut s, params, tables) = setup();
        // Set up near steady state: buffer = generation × delay
        // First compute generation rate
        let generation = {
            let iopc_normalized = s.capital.industrial_output_per_capita / 220.0;
            let gen_ind = s.capital.industrial_output * PPGIO
                * tables.pollution_generation_industry.eval(iopc_normalized);
            let agri_normalized = s.agriculture.agricultural_inputs_per_hectare / 40.0;
            let gen_agri = s.agriculture.arable_land
                * s.agriculture.agricultural_inputs_per_hectare * PPGAO
                * tables.pollution_generation_agriculture.eval(agri_normalized);
            gen_ind + gen_agri
        };
        // Set all 3 stages to steady state: each holds generation * tau
        let tau = POLLUTION_APPEARANCE_DELAY / 3.0;
        s.pollution.pollution_appearance_stage1 = generation * tau;
        s.pollution.pollution_appearance_stage2 = generation * tau;
        s.pollution.pollution_appearance_buffer = generation * tau;
        let (_d_persistent, d_stage1, _d_stage2, _d_stage3) = pollution_derivatives(&mut s, &params, &tables);
        // At steady state, d_stage1 ≈ 0
        assert!(d_stage1.abs() < generation * 0.01,
            "d_stage1 {} should be near zero at steady state (gen={})", d_stage1, generation);
    }

    #[test]
    fn test_pollution_generation_rate_positive() {
        let (mut s, params, tables) = setup();
        pollution_derivatives(&mut s, &params, &tables);
        assert!(s.pollution.generation_rate > 0.0,
            "generation rate should be positive at standard conditions");
    }

    #[test]
    fn test_pollution_control_reduces_generation() {
        let (mut s1, _, tables) = setup();
        let mut params_no_control = ScenarioParams::collapse();
        params_no_control.pollution_control = 0.0;
        pollution_derivatives(&mut s1, &params_no_control, &tables);
        let gen_no_control = s1.pollution.generation_rate;

        let (mut s2, _, _) = setup();
        let mut params_control = ScenarioParams::collapse();
        params_control.pollution_control = 0.8;
        pollution_derivatives(&mut s2, &params_control, &tables);
        let gen_control = s2.pollution.generation_rate;

        // control=0.8 → generation is 20% of uncontrolled
        assert_relative_eq!(gen_control, gen_no_control * 0.2, epsilon = 1e-15);
    }

    #[test]
    fn test_zero_industrial_output_minimal_generation() {
        let (mut s, params, tables) = setup();
        s.capital.industrial_output = 0.0;
        s.capital.industrial_output_per_capita = 0.0;
        pollution_derivatives(&mut s, &params, &tables);
        // Only agricultural pollution remains
        assert!(s.pollution.generation_rate > 0.0,
            "should still have agricultural pollution");
        // Should be much less than with industrial output
        let gen_no_industry = s.pollution.generation_rate;

        let (mut s2, _, _) = setup();
        pollution_derivatives(&mut s2, &params, &tables);
        assert!(gen_no_industry < s2.pollution.generation_rate,
            "generation without industry ({gen_no_industry}) should be less than with ({}))",
            s2.pollution.generation_rate);
    }

    #[test]
    fn test_assimilation_time_increases_with_pollution() {
        let tables = WorldLookupTables::load();
        // At low pollution, assimilation is fast
        let at_low = tables.pollution_assimilation_time.eval(0.1);
        // At high pollution, assimilation is slower (longer time)
        let at_high = tables.pollution_assimilation_time.eval(20.0);
        assert!(at_high > at_low,
            "assimilation time at high pollution ({at_high}) should exceed low ({at_low})");
    }

    #[test]
    fn test_pollution_index_tracks_persistent_pollution() {
        let (mut s, params, tables) = setup();
        s.pollution.persistent_pollution = 5.0;
        pollution_derivatives(&mut s, &params, &tables);
        assert_eq!(s.pollution.pollution_index, 5.0,
            "pollution_index should equal persistent_pollution");
    }

    #[test]
    fn test_buffer_flow_balance() {
        let (mut s, params, tables) = setup();
        let (d_persistent, d_stage1, d_stage2, d_stage3) = pollution_derivatives(&mut s, &params, &tables);
        let generation = s.pollution.generation_rate;
        let tau = POLLUTION_APPEARANCE_DELAY / 3.0;
        let flow_1_to_2 = s.pollution.pollution_appearance_stage1 / tau;
        let flow_2_to_3 = s.pollution.pollution_appearance_stage2 / tau;
        let appearance_rate = s.pollution.pollution_appearance_buffer / tau;
        // d_stage1 = generation - flow_1_to_2
        assert_relative_eq!(d_stage1, generation - flow_1_to_2, epsilon = 1e-15);
        // d_stage2 = flow_1_to_2 - flow_2_to_3
        assert_relative_eq!(d_stage2, flow_1_to_2 - flow_2_to_3, epsilon = 1e-15);
        // d_stage3 = flow_2_to_3 - appearance_rate
        assert_relative_eq!(d_stage3, flow_2_to_3 - appearance_rate, epsilon = 1e-15);
        // d_persistent = appearance_rate - assimilation
        assert_relative_eq!(d_persistent, appearance_rate - s.pollution.assimilation_rate, epsilon = 1e-15);
    }

    #[test]
    fn test_pollution_delay3_pipeline() {
        let (mut s, params, tables) = setup();
        // Load stage1 with pollution, stages 2/3 low
        s.pollution.pollution_appearance_stage1 = 1.0;
        s.pollution.pollution_appearance_stage2 = 0.1;
        s.pollution.pollution_appearance_buffer = 0.01;
        let (_d_persistent, _d_stage1, d_stage2, d_stage3) =
            pollution_derivatives(&mut s, &params, &tables);
        // Stage2 should be filling from stage1
        assert!(d_stage2 > 0.0, "stage2 ({}) should receive flow from stage1", d_stage2);
        // Stage3 should be filling from stage2
        assert!(d_stage3 > 0.0, "stage3 ({}) should receive flow from stage2", d_stage3);
    }

    #[test]
    fn test_high_pollution_net_accumulation() {
        let (mut s, params, tables) = setup();
        // High industrial output → lots of generation
        s.capital.industrial_output = 5e12;
        s.capital.industrial_output_per_capita = 1000.0;
        s.pollution.persistent_pollution = 0.1;
        s.pollution.pollution_index = 0.1;
        s.pollution.pollution_appearance_buffer = 5.0;
        let (d_persistent, _, _, _) = pollution_derivatives(&mut s, &params, &tables);
        // At high generation with low persistent pollution, net should be positive
        assert!(d_persistent > 0.0,
            "d_persistent {d_persistent} should be positive at high generation / low stock");
    }
}
