//! Persistent pollution sector.
//!
//! Pollution is generated by industrial and agricultural activity and
//! assimilated by the environment at a rate that decreases as pollution
//! accumulates. The pollution index affects agricultural yield and life
//! expectancy in the respective sectors.

use crate::lookup::tables::WorldLookupTables;
use crate::model::{params::ScenarioParams, state::WorldState};

/// Pollution generation coefficient per unit industrial output [index_units / USD].
/// Calibrated: at 1970 (industrial_output ≈ 1e12 USD/yr, iopc_norm ≈ 1.0):
///   gen_industry ≈ 1e12 × 3e-13 × 1.0 = 0.30 index_units/yr.
/// This drives pollution_index from ~0.25 in 1900 to ~1.0 by 1970 in BAU.
const PPGIO: f64 = 3.0e-13;

/// Pollution generation coefficient per unit of arable_land × inputs_per_ha.
/// At 1970 (arable_land ≈ 1.2e9 ha, agri_inputs_per_ha ≈ 40 USD/ha):
///   gen_agri ≈ 1.2e9 × 40 × 1.0e-13 = 0.0048 (small relative to industrial)
const PPGAO: f64 = 1.0e-13;

pub fn pollution_derivative(
    state: &mut WorldState,
    params: &ScenarioParams,
    tables: &WorldLookupTables,
) -> f64 {
    // ---- Pollution generation ----
    let iopc_normalized = state.capital.industrial_output_per_capita
        / 200.0_f64.max(1.0); // normalize to ~1970 level
    let agri_normalized = state.agriculture.agricultural_inputs_per_hectare / 40.0; // normalize

    let gen_industry = state.capital.industrial_output
        * PPGIO
        * tables.pollution_generation_industry.eval(iopc_normalized);

    let gen_agriculture = state.agriculture.arable_land
        * state.agriculture.agricultural_inputs_per_hectare
        * PPGAO
        * tables.pollution_generation_agriculture.eval(agri_normalized);

    // Pollution control policy reduces generation
    let control = params.pollution_control.clamp(0.0, 1.0);
    let generation = (gen_industry + gen_agriculture) * (1.0 - control);

    state.pollution.generation_rate = generation;

    // ---- Pollution assimilation ----
    // Assimilation time increases as pollution overwhelms the environment
    let assimilation_time = tables
        .pollution_assimilation_time
        .eval(state.pollution.pollution_index);

    let assimilation = if assimilation_time > 0.0 {
        state.pollution.persistent_pollution / assimilation_time
    } else {
        0.0
    };
    state.pollution.assimilation_rate = assimilation;

    // ---- Update pollution index (auxiliary, not a stock) ----
    // reference_stock = 1.0 so that pollution_index = persistent_pollution directly.
    // Initial persistent_pollution = 0.25 → pollution_index = 0.25 in 1900.
    // Target: pollution_index = 1.0 in 1970, rising to 10-30 by 2040-2060 in BAU.
    state.pollution.pollution_index = state.pollution.persistent_pollution.max(0.0);

    generation - assimilation
}
