//! Persistent pollution sector.
//!
//! Pollution is generated by industrial and agricultural activity, passes
//! through a 20-year appearance delay (World3-03 PPTD), then accumulates
//! as persistent pollution. Assimilation rate decreases as pollution builds.
//!
//! Two ODE stocks: pollution_appearance_buffer (pipeline) and
//! persistent_pollution (appeared, affecting the environment).

use crate::lookup::tables::WorldLookupTables;
use crate::model::{params::ScenarioParams, state::WorldState};

/// Pollution generation coefficient per unit industrial output [index_units / USD].
/// Calibrated: at 1970 (industrial_output ≈ 1e12 USD/yr, iopc_norm ≈ 1.0):
///   gen_industry ≈ 1e12 × 3e-13 × 1.0 = 0.30 index_units/yr.
const PPGIO: f64 = 3.0e-13;

/// Pollution generation coefficient per unit of arable_land × inputs_per_ha.
const PPGAO: f64 = 1.0e-13;

/// Pollution appearance delay [years]. World3-03: PPTD = 20 years.
/// Generated pollution takes this long to become persistent (visible) pollution.
const POLLUTION_APPEARANCE_DELAY: f64 = 20.0;

/// Returns (d_persistent_pollution, d_pollution_appearance_buffer)
pub fn pollution_derivatives(
    state: &mut WorldState,
    params: &ScenarioParams,
    tables: &WorldLookupTables,
) -> (f64, f64) {
    // ---- Pollution generation ----
    // Normalize IOPC to ~1.0 at 1970 level. World3-03 IO70 = 7.9e11 → IOPC70 ≈ $220/person/yr.
    let iopc_normalized = state.capital.industrial_output_per_capita / 220.0;
    let agri_normalized = state.agriculture.agricultural_inputs_per_hectare / 40.0;

    let gen_industry = state.capital.industrial_output
        * PPGIO
        * tables.pollution_generation_industry.eval(iopc_normalized);

    let gen_agriculture = state.agriculture.arable_land
        * state.agriculture.agricultural_inputs_per_hectare
        * PPGAO
        * tables.pollution_generation_agriculture.eval(agri_normalized);

    // Pollution control policy reduces generation
    let control = params.pollution_control.clamp(0.0, 1.0);
    let generation = (gen_industry + gen_agriculture) * (1.0 - control);

    state.pollution.generation_rate = generation;

    // ---- 20-year appearance delay (simplified Delay3 as first-order) ----
    // In World3-03, PPGR feeds into a 3rd-order delay (Delay3) of 20 years.
    // Simplified here as a first-order delay: buffer accumulates generation,
    // drains into persistent_pollution at rate buffer/delay_time.
    let appearance_rate = state.pollution.pollution_appearance_buffer / POLLUTION_APPEARANCE_DELAY;

    // ---- Pollution assimilation ----
    let assimilation_time = tables
        .pollution_assimilation_time
        .eval(state.pollution.pollution_index);

    let assimilation = if assimilation_time > 0.0 {
        state.pollution.persistent_pollution / assimilation_time
    } else {
        0.0
    };
    state.pollution.assimilation_rate = assimilation;

    // ---- Update pollution index (auxiliary) ----
    state.pollution.pollution_index = state.pollution.persistent_pollution.max(0.0);

    // d(buffer)/dt = generation - appearance_rate
    let d_buffer = generation - appearance_rate;
    // d(persistent_pollution)/dt = appearance_rate - assimilation
    let d_persistent = appearance_rate - assimilation;

    (d_persistent, d_buffer)
}
