#!/usr/bin/env python3
"""Bi-traceability: REQ <-> Test coverage checker.

Parses // REQ: annotations from test files and cross-references
docs/product-requirements.md. Outputs a traceability matrix and
fails if any Done requirement has no test coverage.

Usage: python3 scripts/traceability.py [--warn-only] [--check]
"""

import re
import sys
import glob
import os
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
REQS_FILE = REPO_ROOT / "docs" / "product-requirements.md"
MATRIX_FILE = REPO_ROOT / "docs" / "traceability-matrix.md"

# Patterns
REQ_DEF_RE = re.compile(
    r"- \[([x ])\] \*\*(?P<id>REQ-\d+):.*?\*\*"
)
REQ_EXEMPT_RE = re.compile(
    r"- \*Exempt:\*\s*(.+)"
)
REQ_ANNOTATION_RE = re.compile(
    r"//\s*REQ:\s*(REQ-\d+(?:\s*,\s*REQ-\d+)*)"
)

# Test file globs (relative to repo root)
RUST_SRC_GLOB = "crates/*/src/**/*.rs"
RUST_TEST_GLOB = "crates/*/tests/**/*.rs"
TS_GLOB = "frontend/src/**/*.test.ts"


def parse_requirements(path: Path) -> dict[str, dict]:
    """Parse product-requirements.md -> {req_id: {status, exempt, title}}."""
    reqs: dict[str, dict] = {}
    current_section = "Unknown"
    current_req = None

    for line in path.read_text().splitlines():
        if line.startswith("## Done"):
            current_section = "Done"
        elif line.startswith("## In Progress"):
            current_section = "In Progress"
        elif line.startswith("## Planned"):
            current_section = "Planned"

        m = REQ_DEF_RE.search(line)
        if m:
            req_id = m.group("id")
            # Extract title: everything after "REQ-NNN: " up to "**"
            title_m = re.search(r"REQ-\d+:\s*(.+?)\*\*", line)
            title = title_m.group(1).strip() if title_m else ""
            reqs[req_id] = {
                "status": current_section,
                "exempt": None,
                "title": title,
            }
            current_req = req_id
            continue

        if current_req:
            exempt_m = REQ_EXEMPT_RE.search(line)
            if exempt_m:
                reqs[current_req]["exempt"] = exempt_m.group(1).strip()
                current_req = None
            elif line.strip() == "" or line.startswith("- ["):
                current_req = None

    return reqs


def scan_test_files(repo_root: Path) -> dict[str, list[str]]:
    """Scan test files for // REQ: annotations -> {req_id: [file_paths]}."""
    coverage: dict[str, list[str]] = {}

    patterns = [
        (RUST_SRC_GLOB, "rust"),
        (RUST_TEST_GLOB, "rust"),
        (TS_GLOB, "typescript"),
    ]

    for pattern, _lang in patterns:
        for filepath in sorted(glob.glob(str(repo_root / pattern), recursive=True)):
            rel_path = os.path.relpath(filepath, repo_root)
            try:
                content = Path(filepath).read_text()
            except OSError:
                continue

            for m in REQ_ANNOTATION_RE.finditer(content):
                req_ids = [r.strip() for r in m.group(1).split(",")]
                for req_id in req_ids:
                    coverage.setdefault(req_id, [])
                    if rel_path not in coverage[req_id]:
                        coverage[req_id].append(rel_path)

    return coverage


def generate_matrix(
    reqs: dict[str, dict],
    coverage: dict[str, list[str]],
) -> str:
    """Generate markdown traceability matrix."""
    lines = [
        "# Traceability Matrix",
        "",
        "> Auto-generated by `scripts/traceability.py`. Do not edit manually.",
        "",
        "## Forward: REQ -> Tests",
        "",
        "| REQ | Title | Status | Test Files |",
        "|-----|-------|--------|------------|",
    ]

    for req_id in sorted(reqs.keys(), key=lambda r: int(r.split("-")[1])):
        info = reqs[req_id]
        files = coverage.get(req_id, [])
        status = info["status"]
        if info["exempt"]:
            status += f" (exempt: {info['exempt']})"
        file_list = ", ".join(f"`{f}`" for f in files) if files else "\u2014"
        lines.append(f"| {req_id} | {info['title']} | {status} | {file_list} |")

    # Reverse index
    reverse: dict[str, list[str]] = {}
    for req_id, files in coverage.items():
        for f in files:
            reverse.setdefault(f, [])
            if req_id not in reverse[f]:
                reverse[f].append(req_id)

    lines += [
        "",
        "## Reverse: Test -> REQs",
        "",
        "| Test File | REQs Covered |",
        "|-----------|-------------|",
    ]

    for filepath in sorted(reverse.keys()):
        req_list = ", ".join(sorted(reverse[filepath], key=lambda r: int(r.split("-")[1])))
        lines.append(f"| `{filepath}` | {req_list} |")

    # Summary
    done_reqs = [r for r, info in reqs.items() if info["status"] == "Done"]
    covered = [r for r in done_reqs if r in coverage and not reqs[r]["exempt"]]
    exempt = [r for r in done_reqs if reqs[r]["exempt"]]
    uncovered = [r for r in done_reqs if r not in coverage and not reqs[r]["exempt"]]

    lines += [
        "",
        "## Summary",
        "",
        f"- **Done requirements:** {len(done_reqs)}",
        f"- **Covered by tests:** {len(covered)}",
        f"- **Exempt:** {len(exempt)}",
        f"- **Uncovered:** {len(uncovered)}",
    ]

    if uncovered:
        lines.append("")
        lines.append("### Uncovered Done Requirements")
        lines.append("")
        for r in sorted(uncovered, key=lambda r: int(r.split("-")[1])):
            lines.append(f"- {r}: {reqs[r]['title']}")

    lines.append("")
    return "\n".join(lines)


def main() -> int:
    warn_only = "--warn-only" in sys.argv
    check_only = "--check" in sys.argv

    reqs = parse_requirements(REQS_FILE)
    coverage = scan_test_files(REPO_ROOT)
    matrix = generate_matrix(reqs, coverage)

    # Check mode: fail if committed matrix differs from generated
    if check_only:
        if MATRIX_FILE.exists():
            committed = MATRIX_FILE.read_text()
            if committed == matrix:
                print("Traceability matrix is up to date.")
            else:
                print("[FAIL] Traceability matrix is stale. Run `python3 scripts/traceability.py` and commit the result.")
                return 1
        else:
            print("[FAIL] Traceability matrix not found. Run `python3 scripts/traceability.py` and commit the result.")
            return 1
    else:
        MATRIX_FILE.write_text(matrix)
        print(f"Traceability matrix written to {MATRIX_FILE.relative_to(REPO_ROOT)}")

    # Check coverage
    done_reqs = {r: info for r, info in reqs.items() if info["status"] == "Done"}
    uncovered = []
    for req_id, info in sorted(done_reqs.items()):
        if info["exempt"]:
            print(f"  {req_id}: exempt ({info['exempt']})")
            continue
        if req_id not in coverage:
            uncovered.append(req_id)

    total_done = len(done_reqs)
    total_exempt = sum(1 for info in done_reqs.values() if info["exempt"])
    total_covered = total_done - len(uncovered) - total_exempt

    print(f"\nCoverage: {total_covered}/{total_done - total_exempt} Done requirements have tests ({total_exempt} exempt)")

    if uncovered:
        print(f"\nUncovered Done requirements:")
        for req_id in uncovered:
            print(f"  {req_id}: {done_reqs[req_id]['title']}")

        if warn_only:
            print("\n[WARN] Running in warn-only mode, not failing.")
            return 0
        else:
            print("\n[FAIL] All Done requirements must have test coverage.")
            return 1

    print("\n[PASS] All Done requirements have test coverage.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
